apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devapp
  namespace: infra
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: http://gitlab.infra.svc.cluster.local/root/devapp.git
    targetRevision: main
    path: deployments
  destination:
    server: https://kubernetes.default.svc
    namespace: devapp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
