apiVersion: apps/v1
kind: Deployment
metadata:
  name: devapp-web
  namespace: devapp
  labels:
    app: devapp-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devapp-web
  template:
    metadata:
      labels:
        app: devapp-web
    spec:
      imagePullSecrets:
        - name: devapp-registry-auth
      securityContext:
        runAsNonRoot: true
        runAsUser: 101
        runAsGroup: 101
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: devapp-web
        image: nexus-registry.infra.svc.cluster.local:5000/devapp/devapp-web:v3
        imagePullPolicy: IfNotPresent
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 5
          failureThreshold: 3
        resources:
          requests:
            cpu: 25m
            memory: 32Mi
          limits:
            cpu: 250m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: devapp-web
  namespace: devapp
  labels:
    app: devapp-web
spec:
  selector:
    app: devapp-web
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
