---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: devapp-db-credentials
  namespace: devapp
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: devapp-db-credentials
    creationPolicy: Owner
  data:
    - secretKey: DB_USERNAME
      remoteRef:
        key: infra/postgres
        property: username
    - secretKey: DB_PASSWORD
      remoteRef:
        key: infra/postgres
        property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: devapp-registry-auth
  namespace: devapp
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: devapp-registry-auth
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: >-
          {"auths":{"nexus.swirlit.internal:5000":{"username":"{{ .username }}","password":"{{ .password }}","auth":"{{ printf "%s:%s" .username .password | b64enc }}"}}}
  data:
    - secretKey: username
      remoteRef:
        key: infra/registry
        property: pull_username
    - secretKey: password
      remoteRef:
        key: infra/registry
        property: pull_password
