apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: devapp-ci-credentials
  namespace: jenkins-builds
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: devapp-ci-credentials
    creationPolicy: Owner
  data:
    - secretKey: GIT_USERNAME
      remoteRef:
        key: devapp/ci
        property: github_username
    - secretKey: GIT_TOKEN
      remoteRef:
        key: devapp/ci
        property: github_token
