apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - devapp-secrets.yaml
  - user-app.yaml
  - order-app.yaml
  - devapp-web.yaml
  - ingress.yaml
  - observability.yaml
images:
  - name: devapp/user-app
    newTag: observability-v1
  - name: devapp/order-app
    newTag: observability-v1
  - name: devapp/devapp-web
    newTag: bootstrap-ec4d28f
