apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - devapp-secrets.yaml
  - user-app.yaml
  - order-app.yaml
  - devapp-web.yaml
  - network-policy.yaml
  - ingress.yaml
  - observability.yaml
images:
  - name: nexus-registry.infra.svc.cluster.local:5000/devapp/user-app
    newTag: 19-6c63025
  - name: nexus-registry.infra.svc.cluster.local:5000/devapp/order-app
    newTag: 19-6c63025
  - name: nexus-registry.infra.svc.cluster.local:5000/devapp/devapp-web
    newTag: 19-6c63025
