sonar.projectKey=swirlit:swirl-demo-app
sonar.projectName=Swirl Demo App
sonar.sourceEncoding=UTF-8
sonar.sources=swirlapp-common/src/main,swirlapp-user/src/main,swirlapp-order/src/main,swirlapp-web/src
sonar.tests=swirlapp-common/src/test,swirlapp-user/src/test,swirlapp-order/src/test,swirlapp-web/e2e
sonar.java.binaries=swirlapp-common/target/classes,swirlapp-user/target/classes,swirlapp-order/target/classes
sonar.java.libraries=.cache/maven/**/*.jar
sonar.coverage.jacoco.xmlReportPaths=swirlapp-user/target/site/jacoco/jacoco.xml,swirlapp-order/target/site/jacoco/jacoco.xml
sonar.javascript.lcov.reportPaths=swirlapp-web/coverage/swirlapp-web/lcov.info
sonar.exclusions=**/node_modules/**,**/dist/**,**/target/**,**/*.config.ts,**/environment*.ts,**/*.spec.ts
sonar.test.inclusions=**/*Test.java,**/*Tests.java,**/*.spec.ts
sonar.coverage.exclusions=**/config/**,**/dto/**,**/domain/**,**/*Application.java,swirlapp-web/src/main.ts
sonar.scm.provider=git
