sonar.projectKey=swirlit:devapp
sonar.projectName=DevApp
sonar.sourceEncoding=UTF-8
sonar.sources=devapp-common/src/main,user-app/src/main,order-app/src/main,devapp-web/src
sonar.tests=devapp-common/src/test,user-app/src/test,order-app/src/test,devapp-web/e2e
sonar.java.binaries=devapp-common/target/classes,user-app/target/classes,order-app/target/classes
sonar.java.libraries=.cache/maven/**/*.jar
sonar.coverage.jacoco.xmlReportPaths=user-app/target/site/jacoco/jacoco.xml,order-app/target/site/jacoco/jacoco.xml
sonar.javascript.lcov.reportPaths=devapp-web/coverage/devapp-web/lcov.info
sonar.exclusions=**/node_modules/**,**/dist/**,**/target/**,**/*.config.ts,**/environment*.ts,**/*.spec.ts
sonar.test.inclusions=**/*Test.java,**/*Tests.java,**/*.spec.ts
sonar.coverage.exclusions=**/config/**,**/dto/**,**/domain/**,**/*Application.java,devapp-web/src/main.ts
sonar.scm.provider=git
