spring:
  datasource:
    url: jdbc:h2:mem:order-test;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
  sql:
    init:
      mode: never
  cache:
    type: simple
  kafka:
    listener:
      auto-startup: false
app:
  security:
    enabled: false
  messaging:
    enabled: false
