apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: swirlapp-user
spec:
  minAvailable: 1
  unhealthyPodEvictionPolicy: AlwaysAllow
  selector:
    matchLabels:
      app: swirlapp-user
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: swirlapp-order
spec:
  minAvailable: 1
  unhealthyPodEvictionPolicy: AlwaysAllow
  selector:
    matchLabels:
      app: swirlapp-order
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: swirlapp-web
spec:
  minAvailable: 1
  unhealthyPodEvictionPolicy: AlwaysAllow
  selector:
    matchLabels:
      app: swirlapp-web
