apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: devapp-runtime-credentials
  namespace: apps
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: devapp-runtime-credentials
    creationPolicy: Owner
  data:
    - secretKey: DB_USERNAME
      remoteRef:
        key: apps/devapp/prod/database
        property: username
    - secretKey: DB_PASSWORD
      remoteRef:
        key: apps/devapp/prod/database
        property: password
    - secretKey: REDIS_USERNAME
      remoteRef:
        key: apps/devapp/prod/redis
        property: username
    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: apps/devapp/prod/redis
        property: password
    - secretKey: KAFKA_USERNAME
      remoteRef:
        key: apps/devapp/prod/kafka
        property: username
    - secretKey: KAFKA_PASSWORD
      remoteRef:
        key: apps/devapp/prod/kafka
        property: password
