apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps
resources:
  - external-secrets.yaml
  - registry-credentials.yaml
  - user.yaml
  - order.yaml
  - web.yaml
  - network-policy.yaml
  - ingress.yaml
  - observability.yaml
images:
  - name: registry.swirlit.dev/swirlit/devapp/user-app
    newTag: 1.1.8
  - name: registry.swirlit.dev/swirlit/devapp/order-app
    newTag: 1.1.8
  - name: registry.swirlit.dev/swirlit/devapp/devapp-web
    newTag: 1.1.8
