apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps
resources:
  - external-secrets.yaml
  - registry-credentials.yaml
  - database-setup-job.yaml
  - user.yaml
  - order.yaml
  - web.yaml
  - network-policy.yaml
  - ingress.yaml
  - observability.yaml
images:
  - name: registry.swirlit.dev/swirlit/devapp/user-app
    newTag: 1.4.1
  - name: registry.swirlit.dev/swirlit/devapp/order-app
    newTag: 1.4.1
  - name: registry.swirlit.dev/swirlit/devapp/devapp-web
    newTag: 1.4.1
  - name: postgres
    newName: registry.swirlit.dev/swirlit/bm-cluster/security/postgres-client
    digest: sha256:0fbebd30e2814439e79bf53ca0187f2bfd9ff593edbb8a15a5b001daad698bdb
