apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps
resources:
  - external-secrets.yaml
  - registry-credentials.yaml
  - user.yaml
  - order.yaml
  - web.yaml
  - network-policy.yaml
  - ingress.yaml
  - observability.yaml
configMapGenerator:
  - name: devapp-backend-config
    envs:
      - backend-runtime.properties
    options:
      annotations:
        argocd.argoproj.io/sync-wave: "-2"
  - name: devapp-web-config
    files:
      - runtime-config.json=web-runtime-config.json
images:
  - name: registry.swirlit.dev/swirlit/devapp/user-app
    newTag: 1.5.18
  - name: registry.swirlit.dev/swirlit/devapp/order-app
    newTag: 1.5.18
  - name: registry.swirlit.dev/swirlit/devapp/devapp-web
    newTag: 1.5.18
