CREATE TABLE IF NOT EXISTS orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    user_name VARCHAR(120),
    product_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_by VARCHAR(255),
    created_date TIMESTAMP WITH TIME ZONE,
    last_modified_by VARCHAR(255),
    last_modified_date TIMESTAMP WITH TIME ZONE
);
