apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: swirl-demo-app-int
  namespace: infra
  annotations:
    swirl-demo-app.delivery/pipeline: '601'
    swirl-demo-app.delivery/source: c38fd20ba98665cc3fa842c8195686cb69fb9a20
    swirl-demo-app.delivery/kind: snapshot
  labels:
    app.kubernetes.io/name: swirl-demo-app
    app.kubernetes.io/part-of: swirl-demo-app
    swirl-cloud/environment: int
spec:
  project: applications-int
  source:
    repoURL: http://gitlab.swirlit.internal/swirlit/swirl-demo-app.git
    targetRevision: 7d715c00a496887b0cc228a82541047c3ac6af73
    path: infra/environments/int
  destination:
    name: in-cluster
    namespace: apps-int
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
    syncOptions:
    - PruneLast=true
    - FailOnSharedResource=true
