apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: swirl-demo-app-int
  namespace: infra
  annotations:
    swirl-demo-app.delivery/pipeline: '586'
    swirl-demo-app.delivery/source: 5ff3d06a52fbb858d6c55a050bf4a26ecbd82095
    swirl-demo-app.delivery/kind: release
  labels:
    app.kubernetes.io/name: swirl-demo-app
    app.kubernetes.io/part-of: swirl-demo-app
    swirl-cloud/environment: int
spec:
  project: applications-int
  source:
    repoURL: http://gitlab.swirlit.internal/swirlit/swirl-demo-app.git
    targetRevision: 4f036186ed0eaff6e6ec6475a666c62344d971f2
    path: infra/environments/int
  destination:
    name: in-cluster
    namespace: apps-int
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
    syncOptions:
    - PruneLast=true
    - FailOnSharedResource=true
