apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: swirl-demo-app-prod
  namespace: infra
  annotations:
    swirl-demo-app.delivery/pipeline: '599'
    swirl-demo-app.delivery/source: 5ff3d06a52fbb858d6c55a050bf4a26ecbd82095
    swirl-demo-app.delivery/kind: release
  labels:
    app.kubernetes.io/name: swirl-demo-app
    app.kubernetes.io/part-of: swirl-demo-app
    swirl-cloud/environment: prod
spec:
  project: applications-prod
  source:
    repoURL: http://gitlab.swirlit.internal/swirlit/swirl-demo-app.git
    targetRevision: 5c6cc8c770c9ef12ab051b324db2f9a56952be22
    path: infra/environments/prod
  destination:
    name: in-cluster
    namespace: apps-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
    syncOptions:
    - PruneLast=true
    - FailOnSharedResource=true
