apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: swirl-demo-app-uat
  namespace: infra
  annotations:
    swirl-demo-app.delivery/pipeline: '588'
    swirl-demo-app.delivery/source: 5ff3d06a52fbb858d6c55a050bf4a26ecbd82095
    swirl-demo-app.delivery/kind: release
  labels:
    app.kubernetes.io/name: swirl-demo-app
    app.kubernetes.io/part-of: swirl-demo-app
    swirl-cloud/environment: uat
spec:
  project: applications-uat
  source:
    repoURL: http://gitlab.swirlit.internal/swirlit/swirl-demo-app.git
    targetRevision: 7a9a0e173385a45ca675923ea61ad77edb42760f
    path: infra/environments/uat
  destination:
    name: in-cluster
    namespace: apps-uat
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
    syncOptions:
    - PruneLast=true
    - FailOnSharedResource=true
