apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: swirl-demo-app-uat
  namespace: infra
  annotations:
    swirl-demo-app.delivery/pipeline: '601'
    swirl-demo-app.delivery/source: c38fd20ba98665cc3fa842c8195686cb69fb9a20
    swirl-demo-app.delivery/kind: release
  labels:
    app.kubernetes.io/name: swirl-demo-app
    app.kubernetes.io/part-of: swirl-demo-app
    swirl-cloud/environment: uat
spec:
  project: applications-uat
  source:
    repoURL: http://gitlab.swirlit.internal/swirlit/swirl-demo-app.git
    targetRevision: 2b6443ff690521eab5075f6795650f434022e31c
    path: infra/environments/uat
  destination:
    name: in-cluster
    namespace: apps-uat
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
    syncOptions:
    - PruneLast=true
    - FailOnSharedResource=true
